### ISSUE TITLE
[Question/Bug?] `'text'.text.make()` causes crash when `Text('text')` does not

### ISSUE THREAD

**Issue by avkonst** [iampawan/VelocityX#112]
(Thanks for the package. It does help to develop UI faster)

**Describe the bug**
If the following is retuned from the widget build function, it crashes with flutter exception:

```dart
class SettingsPage extends HookWidget {
    
    SettingsPage({Key? key}) : super(key: key);

    @override
    Widget build(BuildContext context) {
        final user = useUser();
        final theme = useTheme();
        final photoUrl = user?.photoUrl;
        final photoSize = context.screenWidth / 3;
        final photoFallback = CircleAvatar(child: Icon(Icons.person, size: photoSize));
        return Scaffold(
            appBar: AppBar(
                title: "settings".text.uppercase.bold.fontFamily("Brand").make(),
            ),
            body: LayoutBuilder(builder: (context, constraints) {
                return SingleChildScrollView(
                    child: ConstrainedBox(
                        constraints: BoxConstraints(minHeight: constraints.maxHeight),
                        child: IntrinsicHeight(
                            child: Column(
                                mainAxisSize: MainAxisSize.max,
                                crossAxisAlignment: CrossAxisAlignment.stretch,
                                children: [
                                    Expanded(
                                        child: 'top'.text.make().box.height(30).make(),
                                    ),
                                    'header'.text.make().box.height(30).make(),
                                    // comment the following line to get rid of the crash
                                    'header'.text.make(),
                                    Text('header'), // but this one works
                                ]
                            ),
                        )
                    )
                );
            })
        );
    }
}
```

**To Reproduce**
1. Render this widget

**Expected behavior**
I would expect `'header'.text.make()` to behave exactly the same as `Text('header')`. At least not to cause the exception

**Console output**
```
/flutter (29236):  └───── ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞══════════════════════
I/flutter (29236): The following assertion was thrown during performLayout():
I/flutter (29236): LayoutBuilder does not support returning intrinsic dimensions.
I/flutter (29236): Calculating the intrinsic dimensions would require running the
I/flutter (29236): layout callback speculatively, which might mutate the live render
I/flutter (29236): object tree.
I/flutter (29236):
I/flutter (29236): The relevant error-causing widget was:
I/flutter (29236):   IntrinsicHeight
I/flutter (29236):
lib\views\page_settings.dart:32
I/flutter (29236):
I/flutter (29236): When the exception was thrown, this was the stack:

I/flutter (29236): #0      _RenderLayoutBuilder._debugThrowIfNotCheckingIntrinsics.<anonymous closure>
package:flutter/…/widgets/layout_builder.dart:390
I/flutter (29236): #1      _RenderLayoutBuilder._debugThrowIfNotCheckingIntrinsics
package:flutter/…/widgets/layout_builder.dart:397
I/flutter (29236): #2      _RenderLayoutBuilder.computeMaxIntrinsicHeight
package:flutter/…/widgets/layout_builder.dart:344
I/flutter (29236): #3      RenderBox._computeIntrinsicDimension.<anonymous closure>
package:flutter/…/rendering/box.dart:1377
I/flutter (29236): #4      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:311:23)
I/flutter (29236): #5      RenderBox._computeIntrinsicDimension
package:flutter/…/rendering/box.dart:1375
I/flutter (29236): #6      RenderBox.getMaxIntrinsicHeight
package:flutter/…/rendering/box.dart:1747
I/flutter (29236): #7      RenderFlex.computeMaxIntrinsicHeight.<anonymous closure>
package:flutter/…/rendering/flex.dart:635
I/flutter (29236): #8      RenderFlex._getIntrinsicSize
package:flutter/…/rendering/flex.dart:543
I/flutter (29236): #9      RenderFlex.computeMaxIntrinsicHeight
package:flutter/…/rendering/flex.dart:632
I/flutter (29236): #10     RenderBox._computeIntrinsicDimension.<anonymous closure>
package:flutter/…/rendering/box.dart:1377
I/flutter (29236): #11     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:311:23)
I/flutter (29236): #12     RenderBox._computeIntrinsicDimension
package:flutter/…/rendering/box.dart:1375
....

```

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Ulefone Armor X5
 - OS: [e.g. iOS8.1] Android
 - Browser [e.g. stock browser, safari] n/a
 - Version [e.g. 22] 10

**Additional context**
Not sure. Just ask if more information is required.

**Comment by iampawan** [comment]
It's an issue with intrinsic widget. Layout builder doesn't support it by default. You can easily fix it by adding .isIntrinsic eg- "text".text.isIntrinsic.make()

**Comment by avkonst** [comment]
Why does `Text(..)` option work? Is not it `'text'.text.make()` the same as `Text('text')`?

**Comment by iampawan** [comment]
It is the same but it uses AutoSizedText to give you a better experience on multi-sized screens and also reduces the chances of overflow issues.

**Comment by avkonst** [comment]
Ok. Thanks. How does isintrinsic fix it?

**Comment by iampawan** [comment]
It's just a hack that when you say isIntrinsic, it uses Text rather than AutoSizedText
