### ISSUE TITLE
Exception caught by rendering library

### ISSUE THREAD

**Issue by abehbatre** [iampawan/VelocityX#115]
hi pawan / everyone .. can you help my problem ..
im new on flutter, and i love velocityX, its save so much my time to some create ui ..

but tbh, i hate every error message, it's distract me to do next task.

```log
======== Exception caught by rendering library =====================================================
The following message was thrown during paint():
Object has been disposed.

The relevant error-causing widget was: 
  VStack file:///Users/Aditya.Pratama/workspace/teacher-mobile/lib/app/modules/dashboard/schedule/dashboard_schedule_view.dart:16:16
When the exception was thrown, this was the stack: 
#0      Canvas._saveLayer (dart:ui/painting.dart:4045:64)
#1      Canvas.saveLayer (dart:ui/painting.dart:4034:7)
#2      _RenderInnerShadow.paint (package:velocity_x/src/flutter/widgets.dart:488:9)
#3      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#4      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
...
The following RenderObject was being processed when the exception was fired: _RenderInnerShadow#9d67d relayoutBoundary=up7
...  needs compositing
...  parentData: offset=Offset(0.0, 272.0); flex=null; fit=null (can use size)
...  constraints: BoxConstraints(0.0<=w<=312.0, 0.0<=h<=Infinity)
...  size: Size(312.0, 195.0)
RenderObject: _RenderInnerShadow#9d67d relayoutBoundary=up7
  needs compositing
  parentData: offset=Offset(0.0, 272.0); flex=null; fit=null (can use size)
  constraints: BoxConstraints(0.0<=w<=312.0, 0.0<=h<=Infinity)
  size: Size(312.0, 195.0)
...  child: RenderPhysicalShape#4d006 relayoutBoundary=up8
...    needs compositing
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(0.0<=w<=312.0, 0.0<=h<=Infinity)
...    layer: PhysicalModelLayer#45ecd
...      engine layer: PhysicalShapeEngineLayer#55663
...      elevation: 2.0
...      color: Color(0xfffafafa)
...    size: Size(312.0, 195.0)
...    elevation: 2.0
...    color: Color(0xfffafafa)
...    shadowColor: Color(0xfffafafa)
...    clipper: ShapeBorderClipper
...    child: RenderCustomPaint#33102 relayoutBoundary=up9
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(0.0<=w<=312.0, 0.0<=h<=Infinity)
...      size: Size(312.0, 195.0)
...      child: _RenderInkFeatures#16ad8 relayoutBoundary=up10
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(0.0<=w<=312.0, 0.0<=h<=Infinity)
...        size: Size(312.0, 195.0)
...        child: RenderConstrainedBox#3cec1 relayoutBoundary=up11
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(0.0<=w<=312.0, 0.0<=h<=Infinity)
...          size: Size(312.0, 195.0)
...          additionalConstraints: BoxConstraints(w=360.0, 0.0<=h<=Infinity)
====================================================================================================

```

code :
```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:gredu_teacher/app/base/resource/color.dart';
import 'package:gredu_teacher/app/reusable/widgets/ex_icons.dart';
import 'package:gredu_teacher/app/reusable/widgets/index.dart';
import 'package:velocity_x/velocity_x.dart';

import 'dashboard_schedule_controller.dart';

class DashboardScheduleView extends GetView<DashboardScheduleController> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomInset: false,
      body: SafeArea(
        child: VStack([
          HeightBox(14),
          HStack(
            [
              "Jadwal".text.headline1(context).semiBold.black.make(),
              Spacer(),
              IconButton(
                onPressed: () => controller.changeDateWithPicker(context),
                icon: Icon(
                  Icons.date_range,
                  color: battleshipGrey,
                ),
              ),
            ],
          ),
          HeightBox(30),

          // TODO : ITEM WEEK
          HStack(
            [
              buildItemWeek(isSelected: true).cornerRadius(8).marginOnly(right: 10),
              buildItemWeek(isSelected: false).cornerRadius(8).marginOnly(right: 10),
              buildItemWeek(isSelected: false).cornerRadius(8).marginOnly(right: 10),
              buildItemWeek(isSelected: false).cornerRadius(8).marginOnly(right: 10),
              buildItemWeek(isSelected: false).cornerRadius(8).marginOnly(right: 10),
              buildItemWeek(isSelected: false).cornerRadius(8).marginOnly(right: 10),
            ],
          ).scrollHorizontal(),
          HeightBox(16),
          "Senin, 21 Desember 2020".text.size(12).color(battleshipGrey).make(),
          HeightBox(8),
          Divider(),
          HeightBox(8),

          // TODO : ITEM CLASS
          HStack([
            buildItemClass("Semua", true).marginOnly(right: 8),
            buildItemClass("Coco", false).marginOnly(right: 8),
            buildItemClass("Alfie", false).marginOnly(right: 8),
            buildItemClass("Sam", false).marginOnly(right: 8),
            buildItemClass("Angel", false).marginOnly(right: 8),
          ]).scrollHorizontal(),

          HeightBox(24),
          // TODO : ITEM SCHEDULE BY TYPE
          buildItemSchedule(context).innerShadow()
        ]).p24(),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add, color: colorWhite),
        onPressed: () {},
      ),
    );
  }

  Material buildItemWeek({bool isSelected = false}) {
    return isSelected
        ? Material(
          child: Container(
              width: 54,
              height: 60,
              color: colorPrimary,
              child: VStack([
                "21".text.size(18).white.semiBold.make().centered(),
                "Sun".text.maxLines(1).size(12).white.make().centered(),
              ]).centered()),
        )
        : Material(
          child: Container(
              width: 54,
              height: 60,
              decoration: BoxDecoration(
                border: Border.all(color: containerGrey),
                borderRadius: BorderRadius.circular(8),
              ),
              child: VStack([
                "21".text.size(18).black.semiBold.make().centered(),
                "Sun".text.maxLines(1).size(12).black.make().centered(),
              ]).centered()),
        );
  }

  ExButtonOutline buildItemClass(className, isSelected) {
    return isSelected
        ? ExButtonOutline(
            btnText: "$className",
            color: colorPrimary,
            bgColor: lightSage,
            radius: 90,
            height: 32,
            textSize: 12,
            onPress: () {},
          )
        : ExButtonOutline(
            btnText: "$className",
            color: battleshipGrey,
            radius: 90,
            height: 32,
            textSize: 12,
            onPress: () {},
          );
  }

  Material buildItemSchedule(BuildContext context) {
    return Material(
      elevation: 2,
      borderRadius: BorderRadius.circular(10),
      child: Container(
        width: context.mq.size.width,
        // decoration: BoxDecoration(
        //   border: Border.all(color: whiteGrey),
        //   borderRadius: BorderRadius.circular(8),
        // ),
        child: VStack(
          [
            "Tema:".text.color(battleshipGrey).size(12).make(),
            "Indahnya Kebersamaan".text.semiBold.size(14).black.make().marginOnly(top: 4),
            HeightBox(12),
            "Subtema:".text.color(battleshipGrey).size(12).make(),
            "Peduli Terhadap Mahluk Hidup".text.semiBold.black.size(14).make().marginOnly(top: 4),
            HeightBox(12),
            HStack(
              [
                Icon(ExIcons.fi_rr_clock, color: containerGrey, size: 16),
                "08:00 - 09:00".text.size(14).makeCentered().marginOnly(left: 8, top: 2),
              ],
            ),
            HeightBox(16),
            HStack(
              [
                Container(
                  width: 41,
                  height: 24,
                  decoration: BoxDecoration(
                    border: Border.all(color: whiteGrey),
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: "4A".text.color(containerGrey).makeCentered(),
                ),
                WidthBox(8),
                Container(
                  width: 91,
                  height: 24,
                  decoration: BoxDecoration(
                    border: Border.all(color: whiteGrey),
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: "Ruangan: A".text.color(containerGrey).makeCentered(),
                ),
              ],
            ),
          ],
        ).p16(),
      ),
    );
  }
}

```

**Comment by iampawan** [comment]
It's not an issue with VelocityX. It's an issue with your way of rendering layout. You are getting constrained issues which means you are not properly setting widths & height or giving infinite values.

**Comment by abehbatre** [comment]
oh i see, when i rotate phone . is showing error -_- 
thankyou .
